export const mockApartments = [{  street: '666 Elm Street',
        unit: '20',
        city: 'Raccoon City',
        state: 'OH',
        square_footage: 5000,
        price: "900",
        bedrooms: 2,
        bathrooms: 2,
        pets: "gremlins only",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/00/Sesame_Street_buildings_%28193090534%29.jpg"
    },
    {  street: '312 Meadow Lane',
        unit: '420',
        city: 'Houston',
        state: 'TX',
        square_footage: 4000,
        price: "1200",
        bedrooms: 6,
        bathrooms: 1,
        pets: "all of them",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/00/Sesame_Street_buildings_%28193090534%29.jpg"
    },
    {  street: '256 John Street',
        unit: '619',
        city: 'New York City',
        state: 'NY',
        square_footage: 3000,
        price: "3000",
        bedrooms: 0,
        bathrooms: 0,
        pets: "nope",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/00/Sesame_Street_buildings_%28193090534%29.jpg"
    }]